language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "5.2"
  - "iojs"
matrix:
  allow_failures:
    - node_js: "iojs"
  fast_finish: true
before_install: npm install -g grunt-cli
install: npm install
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/88d4270d370096be62f6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
sudo: false
#after_script: "istanbul cover ./all-tests.js"
