language: node_js
node_js:
  - '8.11'
matrix:
  fast_finish: true
services: mongodb
cache:
  directories:
    - node_modules
    - $(npm config get prefix)/bin/grunt-cli
install:
  - npm install --no-optional
sudo: false

#after_script: "istanbul cover ./all-tests.js"
