language: node_js
node_js:
  - "6.11"
  - "8.6"
matrix:
#  allow_failures:
#    - node_js: "0.11"
  fast_finish: true
before_install: npm install -g grunt-cli
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
  - npm install
  - npm install -g npm
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/88d4270d370096be62f6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
sudo: false
#after_script: "istanbul cover ./all-tests.js"
