language: node_js
node_js:
  - "6.11"
  - "8.6"
matrix:
  fast_finish: true
cache:
  directories:
    - node_modules
    - $(npm config get prefix)/bin/grunt-cli
before_install: npm install -g grunt-cli
install:
  - npm install --no-optional
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/88d4270d370096be62f6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
sudo: false

#after_script: "istanbul cover ./all-tests.js"
